main: andreiwasfound.godmode.Main
name: GodMode
author: AndreiWasFound
version: 2.0
website: https://www.spigotmc.org/resources/godmode.81882/

commands:
  godmode reload:
    description: Reloads GodMode config
    permission: godmode.reload
  godmode:
    description: Main info about this plugin
  god:
    description: Become invincible
    permission: godmode.use